export const CellFields = [
  { id: 1, figure: null },
  { id: 2, figure: null },
  { id: 3, figure: null },
  { id: 4, figure: { name: "knight", color: "black" } },
  // { id: 4, figure: null },
  { id: 5, figure: null },
  { id: 6, figure: null },
  { id: 7, figure: null },
  { id: 8, figure: null },
  { id: 9, figure: null },
  { id: 10, figure: null },
  // { id: 11, figure: null },
  { id: 11, figure: { name: "pawn", color: "white", isTouched: true } },
  { id: 12, figure: null },
  // { id: 11, figure: { name: "pawn", color: "black", isTouched: false } },
  // { id: 12, figure: { name: "pawn", color: "black", isTouched: false } },
  { id: 13, figure: null },
  { id: 14, figure: null },
  { id: 15, figure: null },
  { id: 16, figure: null },
  { id: 17, figure: null },
  { id: 18, figure: null },
  { id: 19, figure: null },
  { id: 20, figure: null },
  // { id: 20, figure: { name: "pawn", color: "white", isTouched: true } },
  { id: 21, figure: null },
  { id: 22, figure: null },
  { id: 23, figure: null },
  { id: 24, figure: null },
  { id: 25, figure: null },
  { id: 26, figure: null },
  { id: 27, figure: null },
  // { id: 28, figure: null },
  { id: 28, figure: { name: "knight", color: "white" } },
  // { id: 29, figure: null },
  { id: 29, figure: { name: "knight", color: "black" } },
  // { id: 29, figure: { name: "pawn", color: "black", isTouched: true } },
  { id: 30, figure: null },
  { id: 31, figure: null },
  { id: 32, figure: null },
  { id: 33, figure: null },
  { id: 34, figure: null },
  { id: 35, figure: null },
  { id: 36, figure: null },
  { id: 37, figure: { name: "pawn", color: "black", isTouched: true } },
  { id: 38, figure: null },
  { id: 39, figure: null },
  { id: 40, figure: null },
  { id: 41, figure: null },
  { id: 42, figure: null },
  { id: 43, figure: null },
  { id: 44, figure: { name: "pawn", color: "white", isTouched: true } },
  { id: 45, figure: null },
  { id: 46, figure: null },
  { id: 47, figure: null },
  { id: 48, figure: null },
  { id: 49, figure: null },
  { id: 50, figure: null },
  { id: 51, figure: null },
  { id: 52, figure: null },
  { id: 53, figure: null },
  { id: 54, figure: null },
  { id: 55, figure: null },
  { id: 56, figure: null },
  { id: 57, figure: null },
  { id: 58, figure: null },
  { id: 59, figure: null },
  { id: 60, figure: null },
  { id: 61, figure: null },
  { id: 62, figure: null },
  { id: 63, figure: null },
  { id: 64, figure: null },
];
export const COORDINATES = {
  letters: ["a", "b", "c", "d", "e", "f", "g", "h"],
  numbers: ["8", "7", "6", "5", "4", "3", "2", "1"],
};
